inherit_gem:
  niftany: 
   - niftany_rubocop_rspec.yml                                                                                           
   - niftany_rubocop_ruby.yml 

inherit_from:
  - .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 3.4.1
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'bin/**/*'
    - 'spec/support/spec_helpers.rb' # Rubocop bug

Metrics/BlockLength:
  Exclude:
    - 'Guardfile'
    - 'spec/**/*'

Style/HashConversion:
  Exclude:
  - 'lib/metadata_listener/service/tika.rb'

Style/MapToHash:
  Exclude:
  - 'lib/metadata_listener/service/tika.rb'

RSpec/AnyInstance:
  Enabled: false

Performance/AncestorsInclude:
  Enabled: true

Performance/BigDecimalWithNumericArgument:
  Enabled: true

Performance/RedundantSortBlock:
  Enabled: true

Performance/RedundantStringChars:
  Enabled: true

Performance/ReverseFirst:
  Enabled: true

Performance/SortReverse:
  Enabled: true

Performance/Squeeze:
  Enabled: true

Performance/StringInclude:
  Enabled: true
